apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubernetes.io/change-cause: kubectl set image deployment hello-world-python hello-world-python=in27min/hello-world-python:0.0.2.RELEASE
      --record=true
  creationTimestamp: "2020-09-03T07:16:20Z"
  generation: 7
  labels:
    app: hello-world-python
  name: hello-world-python
  namespace: default
  resourceVersion: "1002834"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hello-world-python
  uid: 60aeb4c5-ad49-48be-aaa0-8d3831fa1076
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-world-python
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world-python
    spec:
      containers:
      - image: in27min/hello-world-python:0.0.2.RELEASE
        imagePullPolicy: IfNotPresent
        name: hello-world-python
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-09-05T07:08:41Z"
    lastUpdateTime: "2020-09-05T07:08:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-05T06:31:29Z"
    lastUpdateTime: "2020-09-06T06:00:46Z"
    message: ReplicaSet "hello-world-python-76f8ddd48c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
